### ISSUE TITLE
قدردانی

### ISSUE THREAD

**Issue by AliTabarY** [Azumi67/LocalTun_TCP#1]
سلام
ممنون بابت تمام زحمتا
واقعا کارت درسته
آموزشی هم برامون میزاری ؟ البته عجله ای نیست هرموقع وقت کردی

**Comment by Azumi67** [comment]
سلام. دارم اضافه میکنم . فعلا با ترافیک تست نکردم و فقط برای رفع محدودیت تست کردم. صبر کنید دستوراتش رو میذارم

**Comment by AliTabarY** [comment]
باشه دمتگرم

**Comment by Azumi67** [comment]
دستورات رو اضافه کردم . ممکنه کمی دستورات پیچیده باشه که بعداً برایش اسکریپت میسازم

**Comment by Azumi67** [comment]
دستورات آپدیت شد . اگر براتون سخت بود، صبر کنید تا اسکریپتش رو بسازم

**Comment by AliTabarY** [comment]
مرسی از محبتت

**Comment by AliTabarY** [comment]
راستی میشه مولتی سرور استفاده کرد ازش ؟؟؟
یک ایران رو به 2 خارج زد ؟

**Comment by Azumi67** [comment]
بله میشه اما باید صبر کنید که یکم استراحت کردم اسکریپتش کنم که کار شما راحت بشه .
حالا یک آموزش بهتر میذارم

**Comment by AliTabarY** [comment]
اره دمت گرم زحمتش با خودت
بازم ممنون و خسته نباشی
