### ISSUE TITLE
انتخاب بهترین تانل

### ISSUE THREAD

**Issue by mohammadmovaghari** [Azumi67/LocalTun_TCP#2]
دوست عزیز با سلام و احترام
ممنونم بابت زحماتت
یک سوال ذهن منو درگیر کرده
تمام تانل هایی که زحمت کشیدی جواب میدن اما بهترین تانلی که از تعداد زیاد کاربر (حداقل 300 نفر) پشتیبانی کنه چی هست
پروتوکل مورد استفاده وایرگارد و openvpn هست
تا این لحظه udp2raw تست کردم و reverstls اقای رادکسوت ولی هر 2 اختلال دارن
البته udp2raw بهتر بوده.
ممنون میشم راهنمایی کنی

**Comment by Azumi67** [comment]
سلام. من خودم open VPN با vxlan و IPsec استفاده میکنم و پورت فوروارد ساده که هر چی می‌تونه باشه .
این پروژه هم دایرکت و ریورس، لوکال تانل میسازد . 
و در آخر تجربه ای در فروش ندارم و برای همین نمیتونم در اون زمینه کمکی بکنم .

**Comment by mohammadmovaghari** [comment]
خیر بنده برای فروش عرض نکردم
به جهت کشش و ظرفیت تانل عرض کردم
اینکه هر تانلی یک ظرفیت انتقال دارد یک موضوع فنی هست که شما بهتر میتونین راهنمایی کنین.

**Comment by Azumi67** [comment]
پورت فوروارد و vxlan & ipsec نباید مشکلی باشه . ریست تایمر خوب هم بذارید و مشکلی پیش نمیاد . اگر امکان لود بالانس داشتید هم انجام بدید. اگر هم ovpn هست که هیچی .

**Comment by kalilovers** [comment]
> خیر بنده برای فروش عرض نکردم به جهت کشش و ظرفیت تانل عرض کردم اینکه هر تانلی یک ظرفیت انتقال دارد یک موضوع فنی هست که شما بهتر میتونین راهنمایی کنین.

سلام . هم فوروارد هم تانلی که ایشون قرار داده کشش خوبی دارن شما میتونید از تانل های دیگه هم استفاده کنید موردی که هست برای ترافیک بالا تقسیم ترافیک بین سرور های خارج با ایپی تمیز هستش . اگر تقسیم نکنید یا ایپی ها تمیز نباشه احتمال نوسان شدید و کندی وجود داره یا به مرور به وجود میاد وگرنه vxlan sec یا gretap sec multi ipv4 به عنوان متد لوکال خیلی هم خوب هستش و همین تانل فعلی . بعدشم باید ازشون توی تانل مناسبی استفاده کنید به اضافه تقسیم ترافیک و ایپی تمیز و اقدامات دیگه
