### ISSUE TITLE
ایران اکسس شدن سرورها

### ISSUE THREAD

**Issue by lostsoul6** [Azumi67/LocalTun_TCP#3]
درود وقت بخیر @Azumi67 

جدیدا هر شنبه تعداد زیادی از آی پی های ایران ، ایران اکسس میشن به صورتی که سرور ایران به خارج از کشور ترافیک داره ولی ترافیک خارج به مقصد سرور ایران کاملا بسته میشه . همچنین آی پی سرور ایران در اپراتورهای سیم کارتی مثل همراه اول و ایرانسل هم همزمان مسدود میشه و پینگ نمیشه گرفت ازشون دیگه .

شما تجربه این مورد رو داشتید ؟ 

طبق تحقیقی که ما کردیم ، این اکسس شدن به حجم ترافیک ارتباط ندارد چون سرورهای کم ترافیک هم خورده بودن .
به نوع تانل هم ربط ندارد چون تانل های مختلفی از جمله 6to4 و reverse و rat hole بین اکسسی ها بوده .

شما ایده ای دارید که چطور میشه مانع این قضیه شد ؟ کدام تانل هست که تعداد کانکشن کمتری در لحظه از سرور خارج به سمت ایران ارسال کنه ؟ آیا میشه کاری کرد تعداد کانکشن هایی که در کار کاربران با vpn ایجاد میشه کمتر بشه ؟

من نگاه کردم بعضا به ازای یک کاربر که متصل هست ، حدود 300-400 کانکشن روی سرور میوفته . اگر 100 کاربر باشن حدود 40 هزار کانکشن میشه . چطور میشه محدودترش کرد ؟ مثلا یک سرویس مثل سیسکو به ازای هر کاربر متصل ، خیلی کانکشن های کمتری ایجاد میکنه .

ممنون میشم یه راهنمایی کنید هر هفته شنبه سرور ایران ما اکسس میشه و خیلی اذیت میشیم هر بار عوض کنیم .

**Comment by Azumi67** [comment]
سلام. من چون فروشنده نیستم و استفاده شخصی دارم ، برای من اتفاق نیفتاده و دقیقا نمیشه گفت دلیلش چیه . حتی کانکشن های tls دار و IPsec دار هم پیش اومده اکسس شدن ولی خبرش کم بهم رسیده. پروژه waterwall آقای رادکسوت رو تست بفرمایید .مثل اینکه پروژه ایشون در این زمینه پیشتاز هست .
