### ISSUE TITLE
اسکریپت فوروارد و ریورس ipv4

### ISSUE THREAD

**Issue by persian-michael-scott** [Azumi67/LocalTun_TCP#4]
سلام azumi. ممنون بابت زحمتات
یه اسکریپت نوشتم گفتم بذارم کسی خواست تست کنه .
https://github.com/persian-michael-scott/LocalTun_TCP_Script

**Comment by Azumi67** [comment]
سلام زحمت کشیدید . قرار میدم فقط یک نکته اینکه وقتی smux فعال هست نباید heartbeat و interval فعال باشه چون باعث اختلال میشه . با قرار دادن ping-interval و service-name هم میشه نام سرویس رو داد که در زمان disconnection، کلاینت خودش سرویس رو ریست کنه که کانکشن برقرار بشه. مرسی.
مورد دیگر اینکه هنوز موارد خیلی زیادی هست که باید اضافه کنم مثل ورکر ، IPsec ، ریورس vxlan fou gue بر روی این تانل . Encryption و چند چیز‌ دیگر.

**Comment by persian-michael-scott** [comment]
آها مرسی 
یه سری مشکلات داشت شایدم به خاطر همین تنظیمات اشتباه بوده نمیدونم 
ولی مثلاً میرفتم اسپید تست خیلی مصرف CPU بالا می‌رفت می‌پرید رو ۱۰۰٪ و بعد هم محدود می‌شد سرعت دانلود 
حالا تنظیمات رو انجام دادم دوباره تست میکنم میدارم همینجا 
یه سوال ping-interval به ثانیه ؟
