### ISSUE TITLE
سوال درباره انتقال ترافیک

### ISSUE THREAD

**Issue by Hoseinkhalaj1** [Azumi67/LocalTun_TCP#5]
با سلام و تشکر از شما بابت زحماتتون
من الان از پرایوت ایپی استفاده میکنم و با استفاده از گوست ترافیک رو انتقال میدم.
راه جایگزینی بجای گوست هست که سرعت بهتری داشته باشه؟

**Comment by Azumi67** [comment]
سلام. من به شخصه مصرفم برای گیم و یوتیوب هست . با لوکال‌ تان و vxlan و ipsec وصل میشم و بعد پورت فوروارد میکنم. و راضی هم هستم‌ مورد شما هم که خیلی ها از گوست راضی هستن . شاید سرورتون مشکلاتی یا اختلالاتی داره .
