### ISSUE TITLE
Ipv6 local Hetzner

### ISSUE THREAD

**Issue by AtomicError** [Azumi67/LocalTun_TCP#6]
سلام. @Azumi67 
 نمی دونستم کجا باید پیام بدم بهتون برا همین اینجا میگم و ممکنه که اصلا ربطی به این پروژه نداشته باشه پس شرمنده
خب مشکلم در مورد ایپی ورژن 6 لوکاله
که اصلا قابل انجام نیست رو سرور های هتزنر
من همه راه های اینترنتی رو تست زدم و جوابگو نیست
امیدوارم شما بتونید کمک کنید
چون من واقعا نیازش دارم
ممنون 
ایدی من در تلگرام @ItIsMeAhmad

**Comment by Azumi67** [comment]
سلام. خیلی از افرادی هستند که سرور هتزنر دارند و با همین اسکریپت از لوکال‌تانل ها استفاده میکنند . شما باید بررسی کنید که پرایوت آی‌پی ها توسط اسکریپت یا پنل هتزنر شما بسته نباشد . مورد دیگر اینکه سرور های خارج دیگری را بر روی سرور ایران مربوطه تست کنید .

**Comment by AtomicError** [comment]
> سلام. خیلی از افرادی هستند که سرور هتزنر دارند و با همین اسکریپت از لوکال‌تانل ها استفاده میکنند . شما باید بررسی کنید که پرایوت آی‌پی ها توسط اسکریپت یا پنل هتزنر شما بسته نباشد . مورد دیگر اینکه سرور های خارج دیگری را بر روی سرور ایران مربوطه تست کنید .

سلام. من چندتا اسکریپت از جمله اسکریپت خودتون رو تست کردم. لوکال ورژن 6 ساخته میشه ولی وقتی از ایران خارج و پینگ میگیرم و برعکس در هر دو حالت پینگ نمیده
با روش نت پلن هم ساختم ولی جواب نمیده، پینگ نمیده
در حالی که با همون سرور ایران ولی بجای هتزنره یه سرور از aeza گرفتم. خیلی راحت پینگ داد
هم نت پلن هم اسکریپت خودتون جواب بود
برا همین میگم این مشکل از طرف سرور های هتزنره
و اینکه من خودم در سایت هتزنر ثبت نام نکردم و اکانت ندارم برا همین سرور ها رو از doprox میگیرم برا همین امکان چک کردن پنل رو ندارم
چه کاری میتونم انجام بدم در این حالت؟
خودتون سرور رو یه چک نمیکنید؟

**Comment by Azumi67** [comment]
> > سلام. خیلی از افرادی هستند که سرور هتزنر دارند و با همین اسکریپت از لوکال‌تانل ها استفاده میکنند . شما باید بررسی کنید که پرایوت آی‌پی ها توسط اسکریپت یا پنل هتزنر شما بسته نباشد . مورد دیگر اینکه سرور های خارج دیگری را بر روی سرور ایران مربوطه تست کنید .
> 
> سلام. من چندتا اسکریپت از جمله اسکریپت خودتون رو تست کردم. لوکال ورژن 6 ساخته میشه ولی وقتی از ایران خارج و پینگ میگیرم و برعکس در هر دو حالت پینگ نمیده با روش نت پلن هم ساختم ولی جواب نمیده، پینگ نمیده در حالی که با همون سرور ایران ولی بجای هتزنره یه سرور از aeza گرفتم. خیلی راحت پینگ داد هم نت پلن هم اسکریپت خودتون جواب بود برا همین میگم این مشکل از طرف سرور های هتزنره و اینکه من خودم در سایت هتزنر ثبت نام نکردم و اکانت ندارم برا همین سرور ها رو از doprox میگیرم برا همین امکان چک کردن پنل رو ندارم چه کاری میتونم انجام بدم در این حالت؟ خودتون سرور رو یه چک نمیکنید؟

پرایوت آی‌پی ها بسته است چون بقیه هم سرور های هتزنر دارند و مشکلی ندارند . باید از جایی که سرور ازشون گرفتید باهاشون در میان بذارید .
